### ISSUE TITLE
transfer to the public-transport org

### ISSUE THREAD

**Issue by derhuerst** [envake/db-tickets#1]
Hey!
you [mentioned](https://github.com/public-transport/hafas-client/issues/268#issuecomment-1209643143) that we could move this repo to the public-transport org.

Doing this *might* give it more visibility, and others could take over maintenance if you're sick of it at some point. What do you think?

**Comment by envake** [comment]
Yes, that would be great!

**Comment by envake** [comment]
moved 🚂

**Comment by derhuerst** [comment]
@envake I noticed that the repo doesn't have a license. `package.json` indicates that you want to publish the code as [MIT](https://choosealicense.com/licenses/mit/).

Do you agree to license your contributions as MIT? Then I will push an MIT license.

**Comment by derhuerst** [comment]
Also, what do you think about adding an [Editorconfig](https://editorconfig.org), so that supporting editors will automatically get the (basic) formatting right?
